// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/Learn/tm-tools/src/models/dictionaryModel';
import model_3 from 'D:/Learn/tm-tools/src/.umi/plugin-initialState/@@initialState';
import model_2 from 'D:/Learn/tm-tools/src/models/userModel';

export const models = {
model_1: { namespace: 'dictionaryModel', model: model_1 },
model_3: { namespace: '@@initialState', model: model_3 },
model_2: { namespace: 'userModel', model: model_2 },
} as const
