// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from '/Users/a1234/Learn/tm-tools/src/.umi-production/plugin-initialState/@@initialState';
import model_1 from '/Users/a1234/Learn/tm-tools/src/models/userModel';

export const models = {
model_2: { namespace: '@@initialState', model: model_2 },
model_1: { namespace: 'userModel', model: model_1 },
} as const
