// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { useAntdConfig, useAntdConfigSetter } from 'D:/Learn/tm-tools/src/.umi/plugin-antd';
export { Provider, useModel } from 'D:/Learn/tm-tools/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/Learn/tm-tools/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/Learn/tm-tools/src/.umi/plugin-antd/types.d';
export * from 'D:/Learn/tm-tools/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/Learn/tm-tools/node_modules/.pnpm/@umijs+renderer-react@4.1.0_react-dom@18.1.0_react@18.1.0__react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from 'D:/Learn/tm-tools/node_modules/.pnpm/@umijs+renderer-react@4.1.0_react-dom@18.1.0_react@18.1.0__react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/Learn/tm-tools/node_modules/.pnpm/umi@4.1.0_@babel+core@7.23.7_@types+node@20.11.19_@types+react@18.2.46_eslint@8.56.0_prettier_56gcz6aymoxl44rn5htfpycm34/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
